version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitAPIsProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestGitAPIsProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitapis.integrations:gitSave
  packages:
  - name: TestGitAPIsProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.1002
