version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitAPIsProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestGitAPIsProject
  gitUsername: PoojaAnandGit
  gitBranch: main
